# Generated by Django 3.2.6 on 2021-08-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_project', '0002_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='album',
            new_name='albums',
        ),
    ]
