# Generated by Django 3.2.6 on 2021-08-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_project', '0004_tracks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
